"use client";

import { useState, useRef, useCallback } from "react";
import { getToolBySlug } from "@/config/tools";
import ToolPageLayout from "@/components/tools/ToolPageLayout";

const tool = getToolBySlug("favicon-generator")!;

interface GeneratedFavicon {
  size: number;
  label: string;
  url: string;
}

export default function FaviconGeneratorPage() {
  const [sourceUrl, setSourceUrl] = useState<string | null>(null);
  const [favicons, setFavicons] = useState<GeneratedFavicon[]>([]);
  const [dragActive, setDragActive] = useState(false);
  const [generating, setGenerating] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  const sizes = [
    { size: 16, label: "16×16 — Browser tab" },
    { size: 32, label: "32×32 — Browser tab (Retina)" },
    { size: 48, label: "48×48 — Windows site" },
    { size: 64, label: "64×64 — Windows site (Retina)" },
    { size: 96, label: "96×96 — Google TV" },
    { size: 128, label: "128×128 — Chrome Web Store" },
    { size: 180, label: "180×180 — Apple Touch Icon" },
    { size: 192, label: "192×192 — Android Chrome" },
    { size: 512, label: "512×512 — Android Chrome (Splash)" },
  ];

  const generateFavicons = useCallback((file: File) => {
    setGenerating(true);
    const reader = new FileReader();
    reader.onload = (e) => {
      const img = new Image();
      img.onload = () => {
        setSourceUrl(URL.createObjectURL(file));
        const generated: GeneratedFavicon[] = [];

        for (const { size, label } of sizes) {
          const canvas = document.createElement("canvas");
          canvas.width = size;
          canvas.height = size;
          const ctx = canvas.getContext("2d");
          if (!ctx) continue;

          ctx.imageSmoothingEnabled = true;
          ctx.imageSmoothingQuality = "high";

          const srcAspect = img.width / img.height;
          let sx = 0, sy = 0, sw = img.width, sh = img.height;
          if (srcAspect > 1) {
            sx = (img.width - img.height) / 2;
            sw = img.height;
          } else if (srcAspect < 1) {
            sy = (img.height - img.width) / 2;
            sh = img.width;
          }

          ctx.drawImage(img, sx, sy, sw, sh, 0, 0, size, size);
          generated.push({ size, label, url: canvas.toDataURL("image/png") });
        }

        setFavicons(generated);
        setGenerating(false);
      };
      img.src = e.target?.result as string;
    };
    reader.readAsDataURL(file);
  }, []);

  const handleFiles = useCallback(
    (files: FileList | File[]) => {
      const file = Array.from(files).find((f) => f.type.startsWith("image/"));
      if (file) generateFavicons(file);
    },
    [generateFavicons]
  );

  const downloadFavicon = (fav: GeneratedFavicon) => {
    const link = document.createElement("a");
    link.href = fav.url;
    link.download = `favicon-${fav.size}x${fav.size}.png`;
    link.click();
  };

  const downloadAll = () => {
    favicons.forEach((fav) => downloadFavicon(fav));
  };

  const getHtmlCode = () => {
    return `<!-- Favicon — Generated by ToolsePulse.com -->
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png">
<link rel="icon" type="image/png" sizes="512x512" href="/android-chrome-512x512.png">`;
  };

  const [codeCopied, setCodeCopied] = useState(false);

  const copyCode = async () => {
    await navigator.clipboard.writeText(getHtmlCode());
    setCodeCopied(true);
    setTimeout(() => setCodeCopied(false), 2000);
  };

  return (
    <ToolPageLayout tool={tool}>
      <div className="space-y-6">
        {/* Upload */}
        {!sourceUrl && (
          <div className="rounded-2xl border border-gray-200 bg-white p-6 sm:p-8 shadow-sm">
            <div
              onDragOver={(e) => { e.preventDefault(); setDragActive(true); }}
              onDragLeave={() => setDragActive(false)}
              onDrop={(e) => { e.preventDefault(); setDragActive(false); handleFiles(e.dataTransfer.files); }}
              onClick={() => inputRef.current?.click()}
              className={`drop-zone cursor-pointer ${dragActive ? "active" : ""}`}
            >
              <input
                ref={inputRef}
                type="file"
                accept="image/*"
                className="hidden"
                onChange={(e) => e.target.files && handleFiles(e.target.files)}
              />
              {generating ? (
                <div className="flex flex-col items-center gap-3">
                  <div className="h-10 w-10 animate-spin rounded-full border-4 border-purple-200 border-t-purple-600" />
                  <p className="text-sm text-gray-600">Generating favicons...</p>
                </div>
              ) : (
                <>
                  <div className="inline-flex rounded-full bg-purple-100 p-4 mb-4">
                    <svg className="h-8 w-8 text-purple-600" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M12 21a9.004 9.004 0 0 0 8.716-6.747M12 21a9.004 9.004 0 0 1-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 0 1 7.843 4.582M12 3a8.997 8.997 0 0 0-7.843 4.582m15.686 0A11.953 11.953 0 0 1 12 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0 1 21 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0 1 12 16.5a17.92 17.92 0 0 1-8.716-2.247m0 0A9.015 9.015 0 0 1 3 12c0-1.605.42-3.113 1.157-4.418" />
                    </svg>
                  </div>
                  <p className="text-gray-700 font-medium">Drop an image or click to upload</p>
                  <p className="text-sm text-gray-400 mt-1">Use a square image for best results (PNG, JPG, SVG)</p>
                </>
              )}
            </div>
          </div>
        )}

        {/* Results */}
        {favicons.length > 0 && (
          <>
            {/* Source Preview + Actions */}
            <div className="rounded-2xl border border-gray-200 bg-white p-6 sm:p-8 shadow-sm">
              <div className="flex flex-wrap items-center justify-between gap-4">
                <div className="flex items-center gap-4">
                  <img src={sourceUrl!} alt="Source" className="h-16 w-16 rounded-xl border-2 border-gray-200 object-cover" />
                  <div>
                    <h2 className="text-lg font-semibold text-gray-900">Favicons Generated</h2>
                    <p className="text-sm text-gray-500">{favicons.length} sizes ready to download</p>
                  </div>
                </div>
                <div className="flex gap-3">
                  <button onClick={downloadAll} className="btn-primary py-2.5 px-5">
                    <svg className="mr-2 h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
                    </svg>
                    Download All
                  </button>
                  <button
                    onClick={() => { setSourceUrl(null); setFavicons([]); }}
                    className="btn-secondary py-2.5 px-5"
                  >
                    New Image
                  </button>
                </div>
              </div>
            </div>

            {/* Favicon Grid */}
            <div className="rounded-2xl border border-gray-200 bg-white p-6 sm:p-8 shadow-sm">
              <h3 className="text-sm font-semibold text-gray-900 mb-4">All Sizes</h3>
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {favicons.map((fav) => (
                  <div
                    key={fav.size}
                    className="flex items-center gap-4 rounded-xl border border-gray-200 p-4 hover:bg-gray-50 transition-colors"
                  >
                    <div className="flex h-16 w-16 items-center justify-center rounded-lg bg-gray-100 flex-shrink-0">
                      <img
                        src={fav.url}
                        alt={fav.label}
                        style={{ width: Math.min(fav.size, 48), height: Math.min(fav.size, 48) }}
                        className="image-rendering-pixelated"
                      />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-gray-900">{fav.size}×{fav.size}</p>
                      <p className="text-xs text-gray-500 truncate">{fav.label.split("—")[1]?.trim()}</p>
                    </div>
                    <button
                      onClick={() => downloadFavicon(fav)}
                      className="rounded-lg p-2 text-gray-500 hover:bg-blue-50 hover:text-blue-600 transition-colors flex-shrink-0"
                    >
                      <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
                      </svg>
                    </button>
                  </div>
                ))}
              </div>
            </div>

            {/* HTML Code */}
            <div className="rounded-2xl border border-gray-200 bg-white p-6 sm:p-8 shadow-sm">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-sm font-semibold text-gray-900">HTML Code</h3>
                <button
                  onClick={copyCode}
                  className="text-xs font-medium text-blue-600 hover:text-blue-700 transition-colors"
                >
                  {codeCopied ? "✓ Copied!" : "Copy Code"}
                </button>
              </div>
              <pre className="rounded-xl bg-gray-900 p-4 text-sm text-green-400 overflow-x-auto">
                <code>{getHtmlCode()}</code>
              </pre>
              <p className="mt-3 text-xs text-gray-400">
                Paste this in the {"<head>"} section of your HTML file
              </p>
            </div>
          </>
        )}
      </div>
    </ToolPageLayout>
  );
}
