export type ToolCategory = "pdf" | "image" | "text" | "developer" | "generator" | "ai" | "converter" | "audio";

export interface Tool {
  id: string;
  name: string;
  description: string;
  shortDescription: string;
  slug: string;
  category: ToolCategory;
  icon: string;
  isNew: boolean;
  isPopular: boolean;
  tier: 1 | 2 | 3;
  keywords: string[];
}

export const categories: Record<ToolCategory, { label: string; description: string; icon: string }> = {
  pdf: { label: "PDF Tools", description: "Convert, compress, and merge PDF files", icon: "FileText" },
  image: { label: "Image Tools", description: "Compress, resize, and edit images", icon: "Image" },
  converter: { label: "File Converters", description: "Convert between image, document, and media formats", icon: "ArrowRightLeft" },
  audio: { label: "Audio Tools", description: "Convert, trim, and edit audio files", icon: "Music" },
  text: { label: "Text Tools", description: "Extract, format, and transform text", icon: "Type" },
  generator: { label: "Generators", description: "Generate QR codes, passwords, invoices, and more", icon: "Wand" },
  developer: { label: "Developer Tools", description: "JSON, color, and code utilities", icon: "Code" },
  ai: { label: "AI-Powered", description: "Smart tools powered by artificial intelligence", icon: "Sparkles" },
};

export const tools: Tool[] = [
  // PDF Tools
  {
    id: "pdf-to-word",
    name: "PDF to Word Converter",
    description: "Convert PDF files to editable Word documents instantly. Free, fast, and no file size limits. Your files stay private — all processing happens in your browser.",
    shortDescription: "Convert PDF files to editable Word documents",
    slug: "pdf-to-word",
    category: "pdf",
    icon: "FileText",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["pdf to word", "pdf to docx", "convert pdf", "pdf converter"],
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF Converter",
    description: "Convert Word documents to PDF format in seconds. Preserve formatting perfectly. Free, private, and works entirely in your browser.",
    shortDescription: "Convert Word documents to PDF format",
    slug: "word-to-pdf",
    category: "pdf",
    icon: "FileOutput",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["word to pdf", "docx to pdf", "convert word", "document converter"],
  },
  {
    id: "pdf-compressor",
    name: "PDF Compressor",
    description: "Reduce PDF file size without losing quality. Perfect for email attachments and uploads. Free, fast, and completely private.",
    shortDescription: "Reduce PDF file size instantly",
    slug: "pdf-compressor",
    category: "pdf",
    icon: "FileDown",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["pdf compressor", "compress pdf", "reduce pdf size", "shrink pdf"],
  },
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one document. Drag and drop to reorder pages. Free, unlimited, and no watermarks.",
    shortDescription: "Combine multiple PDFs into one",
    slug: "merge-pdf",
    category: "pdf",
    icon: "FilePlus",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["merge pdf", "combine pdf", "join pdf", "pdf merger"],
  },
  {
    id: "pdf-splitter",
    name: "PDF Splitter",
    description: "Split PDF files into separate pages or custom page ranges. Extract specific pages from any PDF. Free, private, and runs in your browser.",
    shortDescription: "Split PDFs into separate pages",
    slug: "pdf-splitter",
    category: "pdf",
    icon: "FileMinus",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["pdf splitter", "split pdf", "extract pdf pages", "separate pdf pages", "pdf page extractor"],
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG Converter",
    description: "Convert PDF pages to high-quality JPG images. Extract all pages as individual images. Free, no upload needed — processed in your browser.",
    shortDescription: "Convert PDF pages to JPG images",
    slug: "pdf-to-jpg",
    category: "pdf",
    icon: "FileImage",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["pdf to jpg", "pdf to image", "convert pdf to jpeg", "pdf to picture", "extract images from pdf"],
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF Converter",
    description: "Convert JPG and JPEG images to PDF documents. Combine multiple images into a single PDF. Free, instant, and completely private.",
    shortDescription: "Convert JPG images to PDF",
    slug: "jpg-to-pdf",
    category: "pdf",
    icon: "FileOutput",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["jpg to pdf", "jpeg to pdf", "image to pdf", "convert jpg to pdf", "photo to pdf"],
  },
  {
    id: "pdf-page-rotator",
    name: "PDF Page Rotator",
    description: "Rotate PDF pages 90, 180, or 270 degrees. Fix upside-down or sideways scanned pages. Free, instant, and processed locally in your browser.",
    shortDescription: "Rotate PDF pages to any angle",
    slug: "pdf-page-rotator",
    category: "pdf",
    icon: "RotateCw",
    isNew: true,
    isPopular: false,
    tier: 2,
    keywords: ["rotate pdf", "pdf rotator", "rotate pdf pages", "fix pdf orientation", "turn pdf pages"],
  },
  // Image Tools
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress JPEG, PNG, and WebP images without losing quality. Reduce file size by up to 80%. Free, unlimited, and processed locally in your browser.",
    shortDescription: "Compress images without losing quality",
    slug: "image-compressor",
    category: "image",
    icon: "ImageDown",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["image compressor", "compress image", "reduce image size", "compress jpg", "compress png"],
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize images to any dimension. Perfect for social media, websites, and print. Maintains aspect ratio and quality. 100% free and private.",
    shortDescription: "Resize images to exact dimensions",
    slug: "image-resizer",
    category: "image",
    icon: "Maximize",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["image resizer", "resize image", "resize photo", "image dimensions"],
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove image backgrounds instantly with AI. Perfect for product photos, portraits, and design projects. Free and processed in your browser.",
    shortDescription: "Remove image backgrounds with AI",
    slug: "background-remover",
    category: "image",
    icon: "Eraser",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["background remover", "remove background", "transparent background", "bg remover"],
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    description: "Crop images to any size or aspect ratio. Supports preset ratios like 1:1, 4:3, 16:9. Free, instant, and processed in your browser.",
    shortDescription: "Crop images to any size or ratio",
    slug: "image-cropper",
    category: "image",
    icon: "Crop",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["image cropper", "crop image online", "crop photo", "resize crop image", "image crop tool"],
  },
  // File Converters
  {
    id: "jpg-to-png",
    name: "JPG to PNG Converter",
    description: "Convert JPG/JPEG images to PNG format with transparency support. Free, instant, and private — all processing in your browser.",
    shortDescription: "Convert JPG images to PNG format",
    slug: "jpg-to-png",
    category: "converter",
    icon: "ImageDown",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["jpg to png", "jpeg to png", "convert jpg", "image converter"],
  },
  {
    id: "png-to-jpg",
    name: "PNG to JPG Converter",
    description: "Convert PNG images to JPG format. Reduce file size while maintaining quality. Free online converter with no uploads.",
    shortDescription: "Convert PNG images to JPG format",
    slug: "png-to-jpg",
    category: "converter",
    icon: "ImageDown",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["png to jpg", "png to jpeg", "convert png", "image converter"],
  },
  {
    id: "webp-to-png",
    name: "WebP to PNG Converter",
    description: "Convert WebP images to PNG format instantly. Perfect for when you need universal image compatibility. 100% free and private.",
    shortDescription: "Convert WebP images to PNG",
    slug: "webp-to-png",
    category: "converter",
    icon: "ImageDown",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["webp to png", "convert webp", "webp converter"],
  },
  {
    id: "svg-to-png",
    name: "SVG to PNG Converter",
    description: "Convert SVG vector files to PNG raster images. Choose your output resolution. Free, fast, and runs in your browser.",
    shortDescription: "Convert SVG vectors to PNG images",
    slug: "svg-to-png",
    category: "converter",
    icon: "ImageDown",
    isNew: true,
    isPopular: false,
    tier: 2,
    keywords: ["svg to png", "convert svg", "svg converter", "vector to raster"],
  },
  {
    id: "heic-to-jpg",
    name: "HEIC to JPG Converter",
    description: "Convert iPhone HEIC photos to JPG format. Open Apple photos anywhere. Free, instant, no upload required.",
    shortDescription: "Convert iPhone HEIC photos to JPG",
    slug: "heic-to-jpg",
    category: "converter",
    icon: "ImageDown",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["heic to jpg", "heic converter", "iphone photo converter", "heic to jpeg"],
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF Converter",
    description: "Convert one or multiple images to a single PDF document. Supports JPG, PNG, WebP. Arrange pages before converting. Free and private.",
    shortDescription: "Convert images to PDF documents",
    slug: "image-to-pdf",
    category: "converter",
    icon: "FileOutput",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["image to pdf", "jpg to pdf", "png to pdf", "photo to pdf"],
  },
  {
    id: "mp4-to-mp3",
    name: "MP4 to MP3 Converter",
    description: "Extract audio from any video file and save as MP3. Supports MP4, WebM, MOV. Free, instant, and processed entirely in your browser.",
    shortDescription: "Extract audio from video as MP3",
    slug: "mp4-to-mp3",
    category: "converter",
    icon: "Music",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["mp4 to mp3", "video to audio", "extract audio from video", "convert mp4 to mp3", "video to mp3"],
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON Converter",
    description: "Convert CSV files to JSON format instantly. Paste CSV data or upload a file. Free, private, and processed in your browser.",
    shortDescription: "Convert CSV data to JSON format",
    slug: "csv-to-json",
    category: "converter",
    icon: "FileJson",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["csv to json", "convert csv to json", "csv converter", "csv to json online", "csv parser"],
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV Converter",
    description: "Convert JSON arrays to CSV format instantly. Paste JSON data or upload a file. Free, private, and processed in your browser.",
    shortDescription: "Convert JSON data to CSV format",
    slug: "json-to-csv",
    category: "converter",
    icon: "FileSpreadsheet",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["json to csv", "convert json to csv", "json converter", "json to csv online", "json to spreadsheet"],
  },
  {
    id: "video-to-gif",
    name: "Video to GIF Converter",
    description: "Convert video clips to animated GIFs. Adjust FPS, resolution, and duration. Free, private, and processed entirely in your browser.",
    shortDescription: "Convert video clips to animated GIFs",
    slug: "video-to-gif",
    category: "converter",
    icon: "Film",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["video to gif", "mp4 to gif", "convert video to gif", "gif maker", "video gif converter"],
  },
  // Audio Tools
  {
    id: "mp3-converter",
    name: "MP3 Converter",
    description: "Convert audio files to MP3 format. Supports WAV, OGG, FLAC, AAC, and more. Adjust bitrate and quality. 100% browser-based.",
    shortDescription: "Convert any audio file to MP3",
    slug: "mp3-converter",
    category: "audio",
    icon: "Music",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["mp3 converter", "audio converter", "wav to mp3", "convert to mp3"],
  },
  {
    id: "wav-converter",
    name: "WAV Converter",
    description: "Convert audio files to WAV format. High-quality uncompressed audio. Supports MP3, OGG, AAC input. Free and private.",
    shortDescription: "Convert audio files to WAV format",
    slug: "wav-converter",
    category: "audio",
    icon: "Music",
    isNew: true,
    isPopular: false,
    tier: 2,
    keywords: ["wav converter", "mp3 to wav", "convert to wav", "audio converter"],
  },
  {
    id: "audio-trimmer",
    name: "Audio Trimmer",
    description: "Trim and cut audio files to exact timestamps. Visual waveform editor. Supports MP3, WAV, OGG. Free, no upload needed.",
    shortDescription: "Trim and cut audio files",
    slug: "audio-trimmer",
    category: "audio",
    icon: "Music",
    isNew: true,
    isPopular: false,
    tier: 2,
    keywords: ["audio trimmer", "cut audio", "trim mp3", "audio cutter"],
  },
  // Text Tools
  {
    id: "screenshot-to-text",
    name: "Screenshot to Text (OCR)",
    description: "Extract text from screenshots and images using advanced OCR technology. Supports multiple languages. Free, fast, and private.",
    shortDescription: "Extract text from screenshots using OCR",
    slug: "screenshot-to-text",
    category: "text",
    icon: "ScanText",
    isNew: false,
    isPopular: false,
    tier: 1,
    keywords: ["screenshot to text", "ocr", "image to text", "extract text from image"],
  },
  {
    id: "image-to-text",
    name: "Image to Text Extractor",
    description: "Extract text from any image format. Powered by advanced OCR. Supports handwriting, documents, and screenshots. Free and unlimited.",
    shortDescription: "Extract text from any image",
    slug: "image-to-text",
    category: "text",
    icon: "FileSearch",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["image to text", "ocr online", "extract text", "picture to text"],
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and paragraphs instantly. See reading time, speaking time, and keyword density. Free, fast, and private.",
    shortDescription: "Count words, characters, and more",
    slug: "word-counter",
    category: "text",
    icon: "FileSearch",
    isNew: false,
    isPopular: true,
    tier: 2,
    keywords: ["word counter", "character counter", "word count", "count words"],
  },
  // Generators
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    description: "Create custom QR codes for URLs, text, WiFi, email, and more. Download as high-resolution PNG or SVG. Free, no signup required.",
    shortDescription: "Create custom QR codes instantly",
    slug: "qr-code-generator",
    category: "generator",
    icon: "QrCode",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["qr code generator", "create qr code", "qr code maker", "free qr code"],
  },
  {
    id: "invoice-generator",
    name: "Invoice Generator",
    description: "Create professional invoices in seconds. Customize with your logo, payment terms, and tax rates. Download as PDF. Completely free.",
    shortDescription: "Create professional invoices for free",
    slug: "invoice-generator",
    category: "generator",
    icon: "Receipt",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["invoice generator", "free invoice", "create invoice", "invoice maker"],
  },
  {
    id: "resume-builder",
    name: "Resume Builder",
    description: "Build a professional resume in minutes. Choose from modern templates. Download as PDF. Free, no account needed.",
    shortDescription: "Build professional resumes in minutes",
    slug: "resume-builder",
    category: "generator",
    icon: "UserCheck",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["resume builder", "cv builder", "free resume", "resume maker"],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate strong, secure passwords instantly. Customize length, symbols, and complexity. Nothing is stored or transmitted. 100% private.",
    shortDescription: "Generate strong, secure passwords",
    slug: "password-generator",
    category: "generator",
    icon: "Lock",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["password generator", "strong password", "random password", "secure password"],
  },
  {
    id: "youtube-thumbnail-downloader",
    name: "YouTube Thumbnail Downloader",
    description: "Download YouTube video thumbnails in all available resolutions. Just paste the video URL. Free, fast, and no signup required.",
    shortDescription: "Download YouTube thumbnails in HD",
    slug: "youtube-thumbnail-downloader",
    category: "generator",
    icon: "Youtube",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["youtube thumbnail downloader", "download thumbnail", "youtube thumbnail", "video thumbnail"],
  },
  {
    id: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate barcodes in Code 128, EAN-13, UPC-A, Code 39, and ITF-14 formats. Download as PNG or SVG. Free, instant, no signup.",
    shortDescription: "Generate barcodes in multiple formats",
    slug: "barcode-generator",
    category: "generator",
    icon: "ScanLine",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["barcode generator", "create barcode", "barcode maker", "ean barcode", "upc barcode", "code 128"],
  },
  // Developer Tools
  {
    id: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Format, validate, and beautify JSON data instantly. Syntax highlighting, error detection, and minify option. Free developer tool.",
    shortDescription: "Format and validate JSON data",
    slug: "json-formatter",
    category: "developer",
    icon: "Braces",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["json formatter", "json validator", "json beautifier", "format json"],
  },
  {
    id: "color-picker",
    name: "Color Picker & Palette Generator",
    description: "Pick colors from any image, generate beautiful palettes, and convert between HEX, RGB, HSL formats. Free design tool.",
    shortDescription: "Pick colors and generate palettes",
    slug: "color-picker",
    category: "developer",
    icon: "Palette",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["color picker", "color palette generator", "hex color", "rgb to hex"],
  },
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    description: "Generate favicons for your website from any image. Creates all required sizes including ICO, PNG, and Apple Touch icons. Free and instant.",
    shortDescription: "Generate website favicons from images",
    slug: "favicon-generator",
    category: "developer",
    icon: "Globe",
    isNew: false,
    isPopular: false,
    tier: 3,
    keywords: ["favicon generator", "create favicon", "ico generator", "website icon"],
  },
  {
    id: "text-diff-checker",
    name: "Text Diff Checker",
    description: "Compare two texts side by side and see the differences highlighted. Find added, removed, and unchanged lines instantly. Free, private, no signup.",
    shortDescription: "Compare two texts and find differences",
    slug: "text-diff-checker",
    category: "developer",
    icon: "GitCompare",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["text diff", "compare text", "diff checker", "text compare online", "find differences in text"],
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    description: "Encode text to Base64 or decode Base64 back to text instantly. Supports UTF-8 characters. Free, private, no signup needed.",
    shortDescription: "Encode and decode Base64 strings",
    slug: "base64-encoder",
    category: "developer",
    icon: "Binary",
    isNew: true,
    isPopular: false,
    tier: 2,
    keywords: ["base64 encode", "base64 decode", "base64 converter", "base64 online", "encode base64"],
  },
  // AI Tools
  {
    id: "ai-text-rewriter",
    name: "AI Text Rewriter",
    description: "Rewrite and paraphrase text using AI. Change tone, simplify language, or make content more professional. Free AI writing tool.",
    shortDescription: "Rewrite text with AI intelligence",
    slug: "ai-text-rewriter",
    category: "ai",
    icon: "Sparkles",
    isNew: false,
    isPopular: false,
    tier: 3,
    keywords: ["ai text rewriter", "paraphrase tool", "rewrite text", "ai paraphraser"],
  },
  {
    id: "ai-image-upscaler",
    name: "AI Image Upscaler",
    description: "Upscale and enhance image resolution using AI. Make blurry images sharp and clear. Supports up to 4x upscaling. Free and private.",
    shortDescription: "Enhance image quality with AI",
    slug: "ai-image-upscaler",
    category: "ai",
    icon: "Wand",
    isNew: false,
    isPopular: false,
    tier: 3,
    keywords: ["ai image upscaler", "upscale image", "enhance image", "image enhancer"],
  },
  {
    id: "grammar-checker",
    name: "Grammar Checker",
    description: "Check and fix grammar, spelling, and punctuation errors instantly. Improve your writing clarity and style. Free AI-powered tool.",
    shortDescription: "Fix grammar and spelling errors",
    slug: "grammar-checker",
    category: "ai",
    icon: "SpellCheck",
    isNew: false,
    isPopular: false,
    tier: 3,
    keywords: ["grammar checker", "grammar check", "spell check", "fix grammar"],
  },
];

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug);
}

export function getPopularTools(): Tool[] {
  return tools.filter((tool) => tool.isPopular);
}

export function getNewTools(): Tool[] {
  return tools.filter((tool) => tool.isNew);
}

export function getToolsByTier(tier: 1 | 2 | 3): Tool[] {
  return tools.filter((tool) => tool.tier === tier);
}
