export type ToolCategory = "pdf" | "image" | "text" | "developer" | "generator" | "ai";

export interface Tool {
  id: string;
  name: string;
  description: string;
  shortDescription: string;
  slug: string;
  category: ToolCategory;
  icon: string;
  isNew: boolean;
  isPopular: boolean;
  tier: 1 | 2 | 3;
  keywords: string[];
}

export const categories: Record<ToolCategory, { label: string; description: string }> = {
  pdf: { label: "PDF Tools", description: "Convert, compress, and merge PDF files" },
  image: { label: "Image Tools", description: "Compress, resize, and edit images" },
  text: { label: "Text Tools", description: "Extract, format, and transform text" },
  developer: { label: "Developer Tools", description: "Tools built for developers" },
  generator: { label: "Generators", description: "Generate QR codes, passwords, and more" },
  ai: { label: "AI-Powered", description: "Smart tools powered by artificial intelligence" },
};

export const tools: Tool[] = [
  {
    id: "pdf-to-word",
    name: "PDF to Word Converter",
    description: "Convert PDF files to editable Word documents instantly. Free, fast, and no file size limits. Your files stay private — all processing happens in your browser.",
    shortDescription: "Convert PDF files to editable Word documents",
    slug: "pdf-to-word",
    category: "pdf",
    icon: "FileText",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["pdf to word", "pdf to docx", "convert pdf", "pdf converter"],
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF Converter",
    description: "Convert Word documents to PDF format in seconds. Preserve formatting perfectly. Free, private, and works entirely in your browser.",
    shortDescription: "Convert Word documents to PDF format",
    slug: "word-to-pdf",
    category: "pdf",
    icon: "FileOutput",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["word to pdf", "docx to pdf", "convert word", "document converter"],
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress JPEG, PNG, and WebP images without losing quality. Reduce file size by up to 80%. Free, unlimited, and processed locally in your browser.",
    shortDescription: "Compress images without losing quality",
    slug: "image-compressor",
    category: "image",
    icon: "ImageDown",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["image compressor", "compress image", "reduce image size", "compress jpg", "compress png"],
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize images to any dimension. Perfect for social media, websites, and print. Maintains aspect ratio and quality. 100% free and private.",
    shortDescription: "Resize images to exact dimensions",
    slug: "image-resizer",
    category: "image",
    icon: "Maximize",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["image resizer", "resize image", "resize photo", "image dimensions"],
  },
  {
    id: "pdf-compressor",
    name: "PDF Compressor",
    description: "Reduce PDF file size without losing quality. Perfect for email attachments and uploads. Free, fast, and completely private.",
    shortDescription: "Reduce PDF file size instantly",
    slug: "pdf-compressor",
    category: "pdf",
    icon: "FileDown",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["pdf compressor", "compress pdf", "reduce pdf size", "shrink pdf"],
  },
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one document. Drag and drop to reorder pages. Free, unlimited, and no watermarks.",
    shortDescription: "Combine multiple PDFs into one",
    slug: "merge-pdf",
    category: "pdf",
    icon: "FilePlus",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["merge pdf", "combine pdf", "join pdf", "pdf merger"],
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove image backgrounds instantly with AI. Perfect for product photos, portraits, and design projects. Free and processed in your browser.",
    shortDescription: "Remove image backgrounds with AI",
    slug: "background-remover",
    category: "image",
    icon: "Eraser",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["background remover", "remove background", "transparent background", "bg remover"],
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    description: "Create custom QR codes for URLs, text, WiFi, email, and more. Download as high-resolution PNG or SVG. Free, no signup required.",
    shortDescription: "Create custom QR codes instantly",
    slug: "qr-code-generator",
    category: "generator",
    icon: "QrCode",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["qr code generator", "create qr code", "qr code maker", "free qr code"],
  },
  {
    id: "screenshot-to-text",
    name: "Screenshot to Text (OCR)",
    description: "Extract text from screenshots and images using advanced OCR technology. Supports multiple languages. Free, fast, and private.",
    shortDescription: "Extract text from screenshots using OCR",
    slug: "screenshot-to-text",
    category: "text",
    icon: "ScanText",
    isNew: false,
    isPopular: false,
    tier: 1,
    keywords: ["screenshot to text", "ocr", "image to text", "extract text from image"],
  },
  {
    id: "invoice-generator",
    name: "Invoice Generator",
    description: "Create professional invoices in seconds. Customize with your logo, payment terms, and tax rates. Download as PDF. Completely free.",
    shortDescription: "Create professional invoices for free",
    slug: "invoice-generator",
    category: "generator",
    icon: "Receipt",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["invoice generator", "free invoice", "create invoice", "invoice maker"],
  },
  {
    id: "resume-builder",
    name: "Resume Builder",
    description: "Build a professional resume in minutes. Choose from modern templates. Download as PDF. Free, no account needed.",
    shortDescription: "Build professional resumes in minutes",
    slug: "resume-builder",
    category: "generator",
    icon: "UserCheck",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["resume builder", "cv builder", "free resume", "resume maker"],
  },
  {
    id: "image-to-text",
    name: "Image to Text Extractor",
    description: "Extract text from any image format. Powered by advanced OCR. Supports handwriting, documents, and screenshots. Free and unlimited.",
    shortDescription: "Extract text from any image",
    slug: "image-to-text",
    category: "text",
    icon: "FileSearch",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["image to text", "ocr online", "extract text", "picture to text"],
  },
  {
    id: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Format, validate, and beautify JSON data instantly. Syntax highlighting, error detection, and minify option. Free developer tool.",
    shortDescription: "Format and validate JSON data",
    slug: "json-formatter",
    category: "developer",
    icon: "Braces",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["json formatter", "json validator", "json beautifier", "format json"],
  },
  {
    id: "color-picker",
    name: "Color Picker & Palette Generator",
    description: "Pick colors from any image, generate beautiful palettes, and convert between HEX, RGB, HSL formats. Free design tool.",
    shortDescription: "Pick colors and generate palettes",
    slug: "color-picker",
    category: "developer",
    icon: "Palette",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["color picker", "color palette generator", "hex color", "rgb to hex"],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate strong, secure passwords instantly. Customize length, symbols, and complexity. Nothing is stored or transmitted. 100% private.",
    shortDescription: "Generate strong, secure passwords",
    slug: "password-generator",
    category: "generator",
    icon: "Lock",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["password generator", "strong password", "random password", "secure password"],
  },
  {
    id: "youtube-thumbnail-downloader",
    name: "YouTube Thumbnail Downloader",
    description: "Download YouTube video thumbnails in all available resolutions. Just paste the video URL. Free, fast, and no signup required.",
    shortDescription: "Download YouTube thumbnails in HD",
    slug: "youtube-thumbnail-downloader",
    category: "generator",
    icon: "Youtube",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["youtube thumbnail downloader", "download thumbnail", "youtube thumbnail", "video thumbnail"],
  },
  {
    id: "ai-text-rewriter",
    name: "AI Text Rewriter",
    description: "Rewrite and paraphrase text using AI. Change tone, simplify language, or make content more professional. Free AI writing tool.",
    shortDescription: "Rewrite text with AI intelligence",
    slug: "ai-text-rewriter",
    category: "ai",
    icon: "Sparkles",
    isNew: true,
    isPopular: false,
    tier: 3,
    keywords: ["ai text rewriter", "paraphrase tool", "rewrite text", "ai paraphraser"],
  },
  {
    id: "ai-image-upscaler",
    name: "AI Image Upscaler",
    description: "Upscale and enhance image resolution using AI. Make blurry images sharp and clear. Supports up to 4x upscaling. Free and private.",
    shortDescription: "Enhance image quality with AI",
    slug: "ai-image-upscaler",
    category: "ai",
    icon: "Wand",
    isNew: true,
    isPopular: false,
    tier: 3,
    keywords: ["ai image upscaler", "upscale image", "enhance image", "image enhancer"],
  },
  {
    id: "grammar-checker",
    name: "Grammar Checker",
    description: "Check and fix grammar, spelling, and punctuation errors instantly. Improve your writing clarity and style. Free AI-powered tool.",
    shortDescription: "Fix grammar and spelling errors",
    slug: "grammar-checker",
    category: "ai",
    icon: "SpellCheck",
    isNew: true,
    isPopular: false,
    tier: 3,
    keywords: ["grammar checker", "grammar check", "spell check", "fix grammar"],
  },
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    description: "Generate favicons for your website from any image. Creates all required sizes including ICO, PNG, and Apple Touch icons. Free and instant.",
    shortDescription: "Generate website favicons from images",
    slug: "favicon-generator",
    category: "developer",
    icon: "Globe",
    isNew: true,
    isPopular: false,
    tier: 3,
    keywords: ["favicon generator", "create favicon", "ico generator", "website icon"],
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and paragraphs instantly. See reading time, speaking time, and keyword density. Free, fast, and private.",
    shortDescription: "Count words, characters, and more",
    slug: "word-counter",
    category: "text",
    icon: "FileSearch",
    isNew: false,
    isPopular: true,
    tier: 2,
    keywords: ["word counter", "character counter", "word count", "count words"],
  },
];

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug);
}

export function getPopularTools(): Tool[] {
  return tools.filter((tool) => tool.isPopular);
}

export function getNewTools(): Tool[] {
  return tools.filter((tool) => tool.isNew);
}

export function getToolsByTier(tier: 1 | 2 | 3): Tool[] {
  return tools.filter((tool) => tool.tier === tier);
}
