export type ToolCategory = "pdf" | "image" | "text" | "developer" | "generator" | "video" | "ai" | "converter" | "audio";

export interface Tool {
  id: string;
  name: string;
  description: string;
  shortDescription: string;
  slug: string;
  category: ToolCategory;
  icon: string;
  isNew: boolean;
  isPopular: boolean;
  tier: 1 | 2 | 3;
  keywords: string[];
  relatedTools?: string[];
}

export const categories: Record<ToolCategory, { label: string; description: string; icon: string }> = {
  pdf: { label: "PDF Tools", description: "Convert, compress, and merge PDF files", icon: "FileText" },
  image: { label: "Image Tools", description: "Compress, resize, and edit images", icon: "Image" },
  converter: { label: "File Converters", description: "Convert between image, document, and media formats", icon: "ArrowRightLeft" },
  audio: { label: "Audio Tools", description: "Convert, trim, and edit audio files", icon: "Music" },
  text: { label: "Text Tools", description: "Extract, format, and transform text", icon: "Type" },
  generator: { label: "Generators", description: "Generate QR codes, passwords, invoices, and more", icon: "Wand" },
  developer: { label: "Developer Tools", description: "JSON, color, and code utilities", icon: "Code" },
  video: { label: "Video Tools", description: "Compress, convert, and edit videos", icon: "Film" },
  ai: { label: "AI-Powered", description: "Smart tools powered by artificial intelligence", icon: "Sparkles" },
};

export const tools: Tool[] = [
  // PDF Tools
  {
    id: "pdf-unlocker",
    name: "PDF Unlocker",
    description: "Remove password protection and restrictions from PDF files. Unlock PDFs for printing, copying, and editing. Free, instant, processed in your browser.",
    shortDescription: "Remove PDF password and restrictions",
    slug: "pdf-unlocker",
    relatedTools: ["pdf-editor", "pdf-signer", "pdf-compressor", "merge-pdf"],
    category: "pdf",
    icon: "Unlock",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to unlock pdf file", "remove pdf password free", "pdf unlocker online", "unlock pdf for editing", "remove pdf restrictions", "open locked pdf free"],
  },
  {
    id: "pdf-signer",
    name: "PDF Signer",
    description: "Add your signature to any PDF document. Type or draw your signature and place it on any page. Free, private, no signup needed.",
    shortDescription: "Add signatures to PDF documents",
    slug: "pdf-signer",
    relatedTools: ["pdf-editor", "pdf-unlocker", "merge-pdf", "pdf-compressor"],
    category: "pdf",
    icon: "PenLine",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["sign pdf online free", "add signature to pdf", "pdf signer no signup", "electronic signature pdf", "sign document online free", "e-sign pdf free"],
  },
  {
    id: "pdf-editor",
    name: "PDF Editor",
    description: "Add text, annotations, and notes to any PDF. Choose font size, color, and position. Free online PDF editor with no signup required.",
    shortDescription: "Add text and annotations to PDFs",
    slug: "pdf-editor",
    relatedTools: ["pdf-signer", "pdf-unlocker", "pdf-to-word", "merge-pdf"],
    category: "pdf",
    icon: "FileEdit",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["edit pdf online free", "add text to pdf", "pdf editor no signup", "annotate pdf free", "write on pdf online", "modify pdf free"],
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word Converter",
    description: "Convert PDF files to editable Word documents instantly. Free, fast, and no file size limits. Your files stay private — all processing happens in your browser.",
    shortDescription: "Convert PDF files to editable Word documents",
    slug: "pdf-to-word",
    relatedTools: ["word-to-pdf", "pdf-compressor", "merge-pdf", "pdf-splitter"],
    category: "pdf",
    icon: "FileText",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["how to convert pdf to word for free", "change pdf to word document", "turn pdf into editable word", "pdf to word without email signup", "open pdf in word free online", "make pdf editable", "pdf to docx free no watermark"],
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF Converter",
    description: "Convert Word documents to PDF format in seconds. Preserve formatting perfectly. Free, private, and works entirely in your browser.",
    shortDescription: "Convert Word documents to PDF format",
    slug: "word-to-pdf",
    relatedTools: ["pdf-to-word", "pdf-compressor", "image-to-pdf", "jpg-to-pdf"],
    category: "pdf",
    icon: "FileOutput",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["how to save word as pdf", "convert word document to pdf free", "turn word file into pdf", "docx to pdf without microsoft", "make word into pdf online", "word to pdf no signup", "save document as pdf free"],
  },
  {
    id: "pdf-compressor",
    name: "PDF Compressor",
    description: "Reduce PDF file size without losing quality. Perfect for email attachments and uploads. Free, fast, and completely private.",
    shortDescription: "Reduce PDF file size instantly",
    slug: "pdf-compressor",
    relatedTools: ["merge-pdf", "pdf-to-word", "image-compressor", "pdf-splitter"],
    category: "pdf",
    icon: "FileDown",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["how to make pdf file smaller", "reduce pdf size for email", "compress pdf under 5mb", "shrink pdf without losing quality", "pdf too large to email fix", "make pdf smaller free", "reduce pdf file size online"],
  },
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one document. Drag and drop to reorder pages. Free, unlimited, and no watermarks.",
    shortDescription: "Combine multiple PDFs into one",
    slug: "merge-pdf",
    relatedTools: ["pdf-splitter", "pdf-compressor", "pdf-to-word", "image-to-pdf"],
    category: "pdf",
    icon: "FilePlus",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["how to combine pdf files into one", "merge two pdfs together free", "put multiple pdfs into one file", "join pdf pages online", "combine pdf without adobe", "merge pdf files free no signup", "add pages to existing pdf"],
  },
  {
    id: "pdf-splitter",
    name: "PDF Splitter",
    description: "Split PDF files into separate pages or custom page ranges. Extract specific pages from any PDF. Free, private, and runs in your browser.",
    shortDescription: "Split PDFs into separate pages",
    slug: "pdf-splitter",
    relatedTools: ["merge-pdf", "pdf-to-jpg", "pdf-page-rotator", "pdf-compressor"],
    category: "pdf",
    icon: "FileMinus",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to separate pdf pages", "extract one page from pdf", "split pdf into individual pages free", "take pages out of pdf", "save single page from pdf", "pull pages from pdf online", "split pdf without adobe"],
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG Converter",
    description: "Convert PDF pages to high-quality JPG images. Extract all pages as individual images. Free, no upload needed — processed in your browser.",
    shortDescription: "Convert PDF pages to JPG images",
    slug: "pdf-to-jpg",
    relatedTools: ["jpg-to-pdf", "pdf-splitter", "image-compressor", "png-to-jpg"],
    category: "pdf",
    icon: "FileImage",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to save pdf as image", "turn pdf into jpg picture", "convert pdf page to photo", "make image from pdf free", "pdf to jpg high quality", "screenshot pdf as image", "save pdf pages as pictures"],
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF Converter",
    description: "Convert JPG and JPEG images to PDF documents. Combine multiple images into a single PDF. Free, instant, and completely private.",
    shortDescription: "Convert JPG images to PDF",
    slug: "jpg-to-pdf",
    relatedTools: ["pdf-to-jpg", "image-to-pdf", "merge-pdf", "image-compressor"],
    category: "pdf",
    icon: "FileOutput",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to make pdf from photos", "turn pictures into pdf file", "combine images into one pdf", "convert photos to pdf on phone", "make pdf from jpg free", "save photos as pdf document", "multiple images to single pdf"],
  },
  {
    id: "pdf-page-rotator",
    name: "PDF Page Rotator",
    description: "Rotate PDF pages 90, 180, or 270 degrees. Fix upside-down or sideways scanned pages. Free, instant, and processed locally in your browser.",
    shortDescription: "Rotate PDF pages to any angle",
    slug: "pdf-page-rotator",
    relatedTools: ["pdf-splitter", "merge-pdf", "pdf-compressor", "pdf-to-word"],
    category: "pdf",
    icon: "RotateCw",
    isNew: true,
    isPopular: false,
    tier: 2,
    keywords: ["how to flip pdf upside down", "rotate pdf sideways pages", "fix scanned pdf wrong way", "turn pdf page landscape to portrait", "rotate one page in pdf", "pdf scanned sideways how to fix", "change pdf orientation free"],
  },
  // Image Tools
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress JPEG, PNG, and WebP images without losing quality. Reduce file size by up to 80%. Free, unlimited, and processed locally in your browser.",
    shortDescription: "Compress images without losing quality",
    slug: "image-compressor",
    relatedTools: ["image-resizer", "png-to-jpg", "webp-to-png", "background-remover"],
    category: "image",
    icon: "ImageDown",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["how to make image file smaller", "reduce photo size for email", "compress image without losing quality", "make picture smaller kb", "shrink photo file size", "image too large how to fix", "reduce jpg size online free"],
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize images to any dimension. Perfect for social media, websites, and print. Maintains aspect ratio and quality. 100% free and private.",
    shortDescription: "Resize images to exact dimensions",
    slug: "image-resizer",
    relatedTools: ["image-compressor", "image-cropper", "background-remover", "svg-to-png"],
    category: "image",
    icon: "Maximize",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["how to resize photo for passport", "make image 1080x1080", "resize picture for instagram", "change image dimensions online", "make photo smaller pixels", "resize image without losing quality", "custom size image free"],
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove image backgrounds instantly with AI. Perfect for product photos, portraits, and design projects. Free and processed in your browser.",
    shortDescription: "Remove image backgrounds with AI",
    slug: "background-remover",
    relatedTools: ["image-compressor", "image-resizer", "image-cropper", "ai-image-upscaler"],
    category: "image",
    icon: "Eraser",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["how to remove background from picture free", "make image background transparent", "cut out person from photo", "remove white background from logo", "erase background from picture online", "transparent png maker", "remove bg without photoshop"],
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    description: "Crop images to any size or aspect ratio. Supports preset ratios like 1:1, 4:3, 16:9. Free, instant, and processed in your browser.",
    shortDescription: "Crop images to any size or ratio",
    slug: "image-cropper",
    relatedTools: ["image-resizer", "image-compressor", "background-remover", "jpg-to-png"],
    category: "image",
    icon: "Crop",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to crop photo into square", "crop image to specific size", "cut part of picture out", "crop photo for instagram", "trim edges of image online", "crop picture to passport size", "resize and crop image free"],
  },
  // File Converters
  {
    id: "jpg-to-png",
    name: "JPG to PNG Converter",
    description: "Convert JPG/JPEG images to PNG format with transparency support. Free, instant, and private — all processing in your browser.",
    shortDescription: "Convert JPG images to PNG format",
    slug: "jpg-to-png",
    relatedTools: ["png-to-jpg", "webp-to-png", "image-compressor", "svg-to-png"],
    category: "converter",
    icon: "ImageDown",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to change jpg to png", "make jpg transparent background", "convert jpeg to png free", "save jpg as png online", "turn photo into png format", "jpg to png without losing quality"],
  },
  {
    id: "png-to-jpg",
    name: "PNG to JPG Converter",
    description: "Convert PNG images to JPG format. Reduce file size while maintaining quality. Free online converter with no uploads.",
    shortDescription: "Convert PNG images to JPG format",
    slug: "png-to-jpg",
    relatedTools: ["jpg-to-png", "image-compressor", "webp-to-png", "pdf-to-jpg"],
    category: "converter",
    icon: "ImageDown",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to change png to jpg", "convert png to jpeg free", "make png into jpg smaller", "png to jpg reduce file size", "turn png to jpeg online", "save png as jpg without quality loss"],
  },
  {
    id: "webp-to-png",
    name: "WebP to PNG Converter",
    description: "Convert WebP images to PNG format instantly. Perfect for when you need universal image compatibility. 100% free and private.",
    shortDescription: "Convert WebP images to PNG",
    slug: "webp-to-png",
    relatedTools: ["png-to-jpg", "jpg-to-png", "svg-to-png", "image-compressor"],
    category: "converter",
    icon: "ImageDown",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to open webp file", "convert webp to png free", "webp image wont open fix", "change webp to normal image", "save webp as png online", "what is webp how to convert", "webp to png no upload"],
  },
  {
    id: "svg-to-png",
    name: "SVG to PNG Converter",
    description: "Convert SVG vector files to PNG raster images. Choose your output resolution. Free, fast, and runs in your browser.",
    shortDescription: "Convert SVG vectors to PNG images",
    slug: "svg-to-png",
    relatedTools: ["favicon-generator", "webp-to-png", "image-resizer", "jpg-to-png"],
    category: "converter",
    icon: "ImageDown",
    isNew: true,
    isPopular: false,
    tier: 2,
    keywords: ["how to convert svg to png", "save svg as image file", "turn svg into png high resolution", "svg to png transparent background", "export svg as picture", "convert vector to image free"],
  },
  {
    id: "heic-to-jpg",
    name: "HEIC to JPG Converter",
    description: "Convert iPhone HEIC photos to JPG format. Open Apple photos anywhere. Free, instant, no upload required.",
    shortDescription: "Convert iPhone HEIC photos to JPG",
    slug: "heic-to-jpg",
    relatedTools: ["jpg-to-png", "image-compressor", "image-resizer", "background-remover"],
    category: "converter",
    icon: "ImageDown",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["how to open heic file on windows", "convert iphone photo to jpg", "heic wont open how to fix", "change iphone photo format", "heic to jpg free no upload", "open apple photo on android", "convert heic to normal photo"],
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF Converter",
    description: "Convert one or multiple images to a single PDF document. Supports JPG, PNG, WebP. Arrange pages before converting. Free and private.",
    shortDescription: "Convert images to PDF documents",
    slug: "image-to-pdf",
    relatedTools: ["jpg-to-pdf", "merge-pdf", "pdf-to-jpg", "image-compressor"],
    category: "converter",
    icon: "FileOutput",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["how to make pdf from images", "turn photos into pdf document", "combine pictures into pdf file", "scan to pdf from photos", "convert multiple images to pdf", "image to pdf no signup free"],
  },
  {
    id: "mp4-to-mp3",
    name: "MP4 to MP3 Converter",
    description: "Extract audio from any video file and save as MP3. Supports MP4, WebM, MOV. Free, instant, and processed entirely in your browser.",
    shortDescription: "Extract audio from video as MP3",
    slug: "mp4-to-mp3",
    relatedTools: ["mp3-converter", "audio-trimmer", "wav-converter", "video-to-gif"],
    category: "video",
    icon: "Music",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to get audio from video", "extract music from mp4", "save video as mp3 file", "convert youtube video to mp3", "pull audio from video free", "mp4 to mp3 without software", "rip audio from video online"],
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON Converter",
    description: "Convert CSV files to JSON format instantly. Paste CSV data or upload a file. Free, private, and processed in your browser.",
    shortDescription: "Convert CSV data to JSON format",
    slug: "csv-to-json",
    relatedTools: ["json-to-csv", "json-formatter", "base64-encoder", "text-diff-checker"],
    category: "converter",
    icon: "FileJson",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to convert csv to json format", "turn spreadsheet into json", "csv to json for api", "convert excel csv to json free", "parse csv as json online", "csv to json array converter"],
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV Converter",
    description: "Convert JSON arrays to CSV format instantly. Paste JSON data or upload a file. Free, private, and processed in your browser.",
    shortDescription: "Convert JSON data to CSV format",
    slug: "json-to-csv",
    relatedTools: ["csv-to-json", "json-formatter", "base64-encoder", "text-diff-checker"],
    category: "converter",
    icon: "FileSpreadsheet",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to open json in excel", "convert json to spreadsheet", "json to csv for excel", "turn json into csv file", "export json as csv download", "json array to csv columns"],
  },
  {
    id: "video-to-gif",
    name: "Video to GIF Converter",
    description: "Convert video clips to animated GIFs. Adjust FPS, resolution, and duration. Free, private, and processed entirely in your browser.",
    shortDescription: "Convert video clips to animated GIFs",
    slug: "video-to-gif",
    relatedTools: ["mp4-to-mp3", "image-compressor", "image-cropper", "image-resizer"],
    category: "video",
    icon: "Film",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to make gif from video", "turn video clip into gif", "create animated gif from mp4", "video to gif for discord", "make gif from video free no watermark", "convert short video to gif online"],
  },
  {
    id: "video-compressor",
    name: "Video Compressor",
    description: "Compress video files to reduce size while maintaining quality. Supports MP4, WebM, MOV. Free, instant, processed in your browser.",
    shortDescription: "Compress videos to smaller file size",
    slug: "video-compressor",
    category: "video",
    icon: "Minimize2",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to compress video file", "reduce video size for email", "make video smaller free", "compress mp4 online", "shrink video file size", "video compressor no upload"],
    relatedTools: ["video-to-gif", "mp4-to-mp3", "image-compressor", "pdf-compressor"],
  },
  // Audio Tools
  {
    id: "mp3-converter",
    name: "MP3 Converter",
    description: "Convert audio files to MP3 format. Supports WAV, OGG, FLAC, AAC, and more. Adjust bitrate and quality. 100% browser-based.",
    shortDescription: "Convert any audio file to MP3",
    slug: "mp3-converter",
    relatedTools: ["wav-converter", "mp4-to-mp3", "audio-trimmer", "video-to-gif"],
    category: "audio",
    icon: "Music",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["how to convert audio to mp3", "change wav file to mp3", "turn voice recording into mp3", "convert audio file free online", "make any audio into mp3", "ogg to mp3 free converter"],
  },
  {
    id: "wav-converter",
    name: "WAV Converter",
    description: "Convert audio files to WAV format. High-quality uncompressed audio. Supports MP3, OGG, AAC input. Free and private.",
    shortDescription: "Convert audio files to WAV format",
    slug: "wav-converter",
    relatedTools: ["mp3-converter", "mp4-to-mp3", "audio-trimmer", "video-to-gif"],
    category: "audio",
    icon: "Music",
    isNew: true,
    isPopular: false,
    tier: 2,
    keywords: ["how to convert mp3 to wav", "turn audio into wav file", "mp3 to wav for editing", "convert to wav lossless free", "change audio to wav format", "wav file converter online"],
  },
  {
    id: "audio-trimmer",
    name: "Audio Trimmer",
    description: "Trim and cut audio files to exact timestamps. Visual waveform editor. Supports MP3, WAV, OGG. Free, no upload needed.",
    shortDescription: "Trim and cut audio files",
    slug: "audio-trimmer",
    relatedTools: ["mp3-converter", "wav-converter", "mp4-to-mp3", "video-to-gif"],
    category: "audio",
    icon: "Music",
    isNew: true,
    isPopular: false,
    tier: 2,
    keywords: ["how to cut part of a song", "trim mp3 for ringtone", "cut beginning of audio file", "shorten audio clip online", "trim voice recording free", "cut mp3 without software", "remove part of audio file"],
  },
  // Text Tools
  {
    id: "screenshot-to-text",
    name: "Screenshot to Text (OCR)",
    description: "Extract text from screenshots and images using advanced OCR technology. Supports multiple languages. Free, fast, and private.",
    shortDescription: "Extract text from screenshots using OCR",
    slug: "screenshot-to-text",
    relatedTools: ["image-to-text", "pdf-to-word", "word-counter", "grammar-checker"],
    category: "text",
    icon: "ScanText",
    isNew: false,
    isPopular: false,
    tier: 1,
    keywords: ["how to copy text from screenshot", "get text out of image", "screenshot text extractor", "read text from photo online", "copy words from picture", "pull text from screenshot free", "ocr screenshot online"],
  },
  {
    id: "image-to-text",
    name: "Image to Text Extractor",
    description: "Extract text from any image format. Powered by advanced OCR. Supports handwriting, documents, and screenshots. Free and unlimited.",
    shortDescription: "Extract text from any image",
    slug: "image-to-text",
    relatedTools: ["screenshot-to-text", "pdf-to-word", "word-counter", "ai-text-rewriter"],
    category: "text",
    icon: "FileSearch",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["image to text", "ocr online", "extract text", "picture to text"],
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and paragraphs instantly. See reading time, speaking time, and keyword density. Free, fast, and private.",
    shortDescription: "Count words, characters, and more",
    slug: "word-counter",
    relatedTools: ["grammar-checker", "ai-text-rewriter", "text-diff-checker", "screenshot-to-text"],
    category: "text",
    icon: "FileSearch",
    isNew: false,
    isPopular: true,
    tier: 2,
    keywords: ["word counter", "character counter", "word count", "count words"],
  },
  // Generators
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    description: "Create custom QR codes for URLs, text, WiFi, email, and more. Download as high-resolution PNG or SVG. Free, no signup required.",
    shortDescription: "Create custom QR codes instantly",
    slug: "qr-code-generator",
    relatedTools: ["barcode-generator", "invoice-generator", "password-generator", "favicon-generator"],
    category: "generator",
    icon: "QrCode",
    isNew: false,
    isPopular: true,
    tier: 1,
    keywords: ["qr code generator", "create qr code", "qr code maker", "free qr code"],
  },
  {
    id: "invoice-generator",
    name: "Invoice Generator",
    description: "Create professional invoices in seconds. Customize with your logo, payment terms, and tax rates. Download as PDF. Completely free.",
    shortDescription: "Create professional invoices for free",
    slug: "invoice-generator",
    relatedTools: ["resume-builder", "qr-code-generator", "pdf-compressor", "word-to-pdf"],
    category: "generator",
    icon: "Receipt",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["how to make invoice for free", "create professional invoice online", "free invoice template pdf", "invoice generator no signup", "make invoice for freelance work", "simple invoice maker free", "send invoice without software"],
  },
  {
    id: "resume-builder",
    name: "Resume Builder",
    description: "Build a professional resume in minutes. Choose from modern templates. Download as PDF. Free, no account needed.",
    shortDescription: "Build professional resumes in minutes",
    slug: "resume-builder",
    relatedTools: ["invoice-generator", "word-to-pdf", "pdf-compressor", "grammar-checker"],
    category: "generator",
    icon: "UserCheck",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["how to make resume for free", "create professional resume online", "build cv without word", "free resume builder no signup", "make resume pdf download", "resume template free no account", "simple resume maker for job"],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate strong, secure passwords instantly. Customize length, symbols, and complexity. Nothing is stored or transmitted. 100% private.",
    shortDescription: "Generate strong, secure passwords",
    slug: "password-generator",
    relatedTools: ["qr-code-generator", "base64-encoder", "barcode-generator", "favicon-generator"],
    category: "generator",
    icon: "Lock",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["how to create strong password", "generate random password free", "make secure password online", "password generator 16 characters", "create uncrackable password", "random password with symbols", "strong wifi password generator"],
  },
  {
    id: "youtube-thumbnail-downloader",
    name: "YouTube Thumbnail Downloader",
    description: "Download YouTube video thumbnails in all available resolutions. Just paste the video URL. Free, fast, and no signup required.",
    shortDescription: "Download YouTube thumbnails in HD",
    slug: "youtube-thumbnail-downloader",
    relatedTools: ["image-compressor", "image-resizer", "image-cropper", "background-remover"],
    category: "generator",
    icon: "Youtube",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["how to download youtube thumbnail", "save youtube video thumbnail", "get thumbnail from youtube link", "youtube thumbnail grabber", "download video thumbnail hd", "extract youtube cover image"],
  },
  {
    id: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate barcodes in Code 128, EAN-13, UPC-A, Code 39, and ITF-14 formats. Download as PNG or SVG. Free, instant, no signup.",
    shortDescription: "Generate barcodes in multiple formats",
    slug: "barcode-generator",
    relatedTools: ["qr-code-generator", "invoice-generator", "password-generator", "favicon-generator"],
    category: "generator",
    icon: "ScanLine",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to make barcode for product", "create barcode free online", "barcode generator for inventory", "make ean 13 barcode", "print barcode for label", "generate upc code free", "barcode maker no signup"],
  },
  // Developer Tools
  {
    id: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Format, validate, and beautify JSON data instantly. Syntax highlighting, error detection, and minify option. Free developer tool.",
    shortDescription: "Format and validate JSON data",
    slug: "json-formatter",
    relatedTools: ["csv-to-json", "json-to-csv", "base64-encoder", "text-diff-checker"],
    category: "developer",
    icon: "Braces",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["how to format messy json", "make json readable online", "validate json syntax free", "prettify json code", "json formatter with error line", "fix json format online", "beautify minified json"],
  },
  {
    id: "color-picker",
    name: "Color Picker & Palette Generator",
    description: "Pick colors from any image, generate beautiful palettes, and convert between HEX, RGB, HSL formats. Free design tool.",
    shortDescription: "Pick colors and generate palettes",
    slug: "color-picker",
    relatedTools: ["favicon-generator", "svg-to-png", "background-remover", "image-cropper"],
    category: "developer",
    icon: "Palette",
    isNew: false,
    isPopular: false,
    tier: 2,
    keywords: ["how to find hex code of color", "pick color from screen online", "convert rgb to hex code", "what color is this hex", "color code finder free", "get exact color from image", "html color picker tool"],
  },
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    description: "Generate favicons for your website from any image. Creates all required sizes including ICO, PNG, and Apple Touch icons. Free and instant.",
    shortDescription: "Generate website favicons from images",
    slug: "favicon-generator",
    relatedTools: ["svg-to-png", "image-resizer", "color-picker", "qr-code-generator"],
    category: "developer",
    icon: "Globe",
    isNew: false,
    isPopular: false,
    tier: 3,
    keywords: ["how to make favicon for website", "create favicon from image", "generate favicon all sizes", "make website tab icon", "favicon generator from png", "create ico file online free", "website icon maker"],
  },
  {
    id: "text-diff-checker",
    name: "Text Diff Checker",
    description: "Compare two texts side by side and see the differences highlighted. Find added, removed, and unchanged lines instantly. Free, private, no signup.",
    shortDescription: "Compare two texts and find differences",
    slug: "text-diff-checker",
    relatedTools: ["json-formatter", "word-counter", "grammar-checker", "base64-encoder"],
    category: "developer",
    icon: "GitCompare",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["how to compare two texts", "find difference between two documents", "text comparison tool online", "what changed between two versions", "compare code side by side free", "spot differences in text", "diff checker no signup"],
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    description: "Encode text to Base64 or decode Base64 back to text instantly. Supports UTF-8 characters. Free, private, no signup needed.",
    shortDescription: "Encode and decode Base64 strings",
    slug: "base64-encoder",
    relatedTools: ["json-formatter", "text-diff-checker", "csv-to-json", "password-generator"],
    category: "developer",
    icon: "Binary",
    isNew: true,
    isPopular: false,
    tier: 2,
    keywords: ["how to decode base64 string", "base64 to text converter", "encode text to base64 online", "what does base64 mean decode it", "convert base64 to readable text", "base64 encoder decoder free"],
  },
  // AI Tools
  {
    id: "ai-text-rewriter",
    name: "AI Text Rewriter",
    description: "Rewrite and paraphrase text using AI. Change tone, simplify language, or make content more professional. Free AI writing tool.",
    shortDescription: "Rewrite text with AI intelligence",
    slug: "ai-text-rewriter",
    relatedTools: ["grammar-checker", "word-counter", "ai-image-upscaler", "text-diff-checker"],
    category: "ai",
    icon: "Sparkles",
    isNew: false,
    isPopular: false,
    tier: 3,
    keywords: ["how to rewrite text in different words", "paraphrase my sentence free", "ai rewrite text for me", "make my writing sound professional", "rephrase paragraph online", "change wording of text free", "reword my essay without plagiarism"],
  },
  {
    id: "ai-image-upscaler",
    name: "AI Image Upscaler",
    description: "Upscale and enhance image resolution using AI. Make blurry images sharp and clear. Supports up to 4x upscaling. Free and private.",
    shortDescription: "Enhance image quality with AI",
    slug: "ai-image-upscaler",
    relatedTools: ["image-compressor", "image-resizer", "background-remover", "ai-text-rewriter"],
    category: "ai",
    icon: "Wand",
    isNew: false,
    isPopular: false,
    tier: 3,
    keywords: ["how to make blurry image clear", "enhance low quality photo", "upscale image without losing quality", "make small image bigger and sharp", "improve photo resolution free", "fix blurry picture online", "ai image enhancer no signup"],
  },
  {
    id: "grammar-checker",
    name: "Grammar Checker",
    description: "Check and fix grammar, spelling, and punctuation errors instantly. Improve your writing clarity and style. Free AI-powered tool.",
    shortDescription: "Fix grammar and spelling errors",
    slug: "grammar-checker",
    relatedTools: ["ai-text-rewriter", "word-counter", "text-diff-checker", "screenshot-to-text"],
    category: "ai",
    icon: "SpellCheck",
    isNew: false,
    isPopular: false,
    tier: 3,
    keywords: ["check my grammar free", "fix grammar mistakes in my text", "grammar checker no signup", "is my sentence grammatically correct", "proofread my essay online", "free spell and grammar check", "correct my english writing"],
  },
  {
    id: "essay-writer",
    name: "AI Essay Writer",
    description: "Generate well-structured essays on any topic with AI. Choose tone, length, and style. Free, instant, no signup required.",
    shortDescription: "Generate essays on any topic with AI",
    slug: "essay-writer",
    relatedTools: ["paragraph-generator", "ai-text-rewriter", "grammar-checker", "word-counter"],
    category: "ai",
    icon: "PenLine",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["ai essay writer free", "write my essay for me", "essay generator no signup", "free essay writer online", "ai write essay on topic", "automatic essay writer", "generate essay for school"],
  },
  {
    id: "paragraph-generator",
    name: "AI Paragraph Generator",
    description: "Generate well-written paragraphs on any topic. Choose from informative, descriptive, narrative, or argumentative styles. Free and instant.",
    shortDescription: "Generate paragraphs on any topic with AI",
    slug: "paragraph-generator",
    relatedTools: ["essay-writer", "ai-text-rewriter", "grammar-checker", "word-counter"],
    category: "ai",
    icon: "AlignLeft",
    isNew: true,
    isPopular: false,
    tier: 1,
    keywords: ["paragraph generator free", "write a paragraph for me", "ai paragraph writer", "generate paragraph about topic", "free paragraph generator online", "auto paragraph writer"],
  },
];

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug);
}

export function getPopularTools(): Tool[] {
  return tools.filter((tool) => tool.isPopular);
}

export function getNewTools(): Tool[] {
  return tools.filter((tool) => tool.isNew);
}

export function getToolsByTier(tier: 1 | 2 | 3): Tool[] {
  return tools.filter((tool) => tool.tier === tier);
}
